### ISSUE TITLE
contry pages + homepage underneath the map: font sizes are too big

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#1]
should be reduced (this does not apply to the footer)

**Comment by mookl** [comment]
What do you mean? You want more columns?

**Comment by mookl** [comment]
Totally disagree. Body text is already reduced to 20px. Which is smaller than most modern websites. If you persist we could settle for 18px.

**Comment by paul2keller** [comment]
i dont know what kind of websites you vist, but those that i generally have text with a text size of about 14 (same size as this bit of text). that is a normal text size for presenting information to readers, so can we try how it looks with 14px as a baseline?

**Comment by mookl** [comment]
![image](https://cloud.githubusercontent.com/assets/13234593/16332615/2322bc26-39f7-11e6-92d7-30bea5f35f2b.png)

It depends on the amount of text on the website. For small samples of text (like on the homepage) it's common to choose a bigger font size. For example: http://www.innovatieimpulsonderwijs.nl/e-didactiek-en-inzet-ict/ (20px); even Communia has 18px (http://www.communia-association.org/). I would settle for 18px then (line-height 26px):

![image](https://cloud.githubusercontent.com/assets/13234593/16332690/9e9a086e-39f7-11e6-83c6-8678515ddb5d.png)

**Comment by paul2keller** [comment]
so can we try 18px on home and 16px on the country pages then (to see how that looks). and downsize the headings etc. accordingly. can one of you change this on the dev site so i can take another look? (impossible to judge based on screenshots.

**Comment by mzeinstra** [comment]
@mookl hoe groot zijn de kopjes op 18px en 16px lopende tekst?

**Comment by mookl** [comment]
@mzeinstra About enzo bedoel je? Bij 18px kan die gewoon 60px blijven. 16px vind ik echt te klein.

**Comment by paul2keller** [comment]
looks good to me now (and @mookl seems to be able to live with it as well)

**Comment by mookl** [comment]
To be clear: 16px for the list-page and 18px for the text under About etc.
