### ISSUE TITLE
country pages: the symbol (checkmark) is too big (high) 

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#10]
<img width="937" alt="screen shot 2016-06-22 at 15 21 17" src="https://cloud.githubusercontent.com/assets/5593766/16268105/40326444-388d-11e6-9b18-eb8b5be02ce0.png">

the checkmark should not extend beyond the height of the line with the article number. So that the line below 'Implemented... ' aligns with the rest of the text underneath.

**Comment by paul2keller** [comment]
this obviously also applies to the other two symbols

**Comment by mookl** [comment]
Yes, makes sense. Although I like the big icons. Gives the page some body. I would rather keep them big and make sure 'Implemented' starts on a new row in line with the rest.

**Comment by paul2keller** [comment]
for my taste the checkmark is also too big. lets try a smaller version and see how that looks

**Comment by mookl** [comment]
Maarten, kun je eens kijken hoe het eruitziet op 50% en met Implemented niet ingesprongen?

**Comment by mzeinstra** [comment]
Like this?

![image](https://cloud.githubusercontent.com/assets/5627431/16274438/e06e6896-38a5-11e6-9c56-dbfc0d2814c2.png)

**Comment by mookl** [comment]
I like it.

**Comment by paul2keller** [comment]
looks good to me
