### ISSUE TITLE
Proper names for exceptions

### ISSUE THREAD

**Issue by mzeinstra** [Kennisland/Copyrightexceptions.eu#13]
@paul2keller we hebben nu deze:

```
5.1 Temporary acts of reproduction
5.2(a) Photocopying/photo-reproduction
5.2(b) Private copying
5.2(c) Library and archive use
5.2(d) Broadcasters 
5.2(e) Reproduction of broadcasts by social institutions 
5.3(a) Teaching/scientific research.Non-commercial 
5.3(b) Disability.Non-commercial 
5.3(c) Press reproduction 
5.3(d) Quotation for criticism or review 
5.3(e) Public security 
5.3(f) Use of political speeches.public lectures 
5.3(g) Religious/celebratory 
5.3(h) Architecture/sculpture for public structures 
5.3(i) Incidental inclusion 
5.3(j) Advertising exhibition or sale 
5.3(k) Caricature,parody or pastiche 
5.3(l) Demonstration/repair of equipment 
5.3(m) Building reconstruction 
5.3(n) Archive exception 
5.3(o) Pre-existing exceptions
Orphan Works
```

Doe jij een voorstel?

**Comment by paul2keller** [comment]
here is my attempt (but i think we need to check this with someone like Lucy (or even someone at the commission). They are slightly longer than yours although the maximum length stays the same (except for 5(3)n where is suggest we leave the part in [ ]'s away): 

5.1 Temporary acts of reproduction
5.2(a) Photocopying/photo-reproduction
5.2(b) Private copying
5.2(c) Reproductions by Libraries, Archives & Museums
5.2(d) Ephemeral recordings made by broadcasters
5.2(e) Reproduction of broadcasts by social institutions 
5.3(a) Illustration for teaching or scientific research 
5.3(b) Use for the benefit of people with a disability
5.3(c) Reporting by the press on current events
5.3(d) Quotation for criticism or review 
5.3(e) Use for public security purposes
5.3(f) Use of public speeches and public lectures 
5.3(g) Use during religious or official celebrations
5.3(h) Use of works of architecture or sculptures in public spaces
5.3(i) Incidental inclusion 
5.3(j) Use for advertising the exhibition or sale of works of art
5.3(k) Use for the purpose of caricature, parody or pastiche
5.3(l) Use for the demonstration or repair of equipment
5.3(m) Use for the purpose of reconstructing a building
5.3(n) Use for the purpose of research or private study [of works held by Libraries Museums or Archives]
5.3(o) Pre-existing exceptions of minor importance
Reproducing and making available of orphan works

**Comment by mzeinstra** [comment]
I'll check with Lucie. requires some refactoring of the tool.

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/17057427/1b8e898e-501a-11e6-95ea-4b7a208181f9.png)
