### ISSUE TITLE
Table view: Country code in the top row should be highlghted on mouse over of a cell in that column

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#15]
same behaviour as the names of the exceptions in the left most column

**Comment by mzeinstra** [comment]
To difficult to accomplish this week.

**Comment by paul2keller** [comment]
but is it possible in principle and you agree that we should do this?

**Comment by mzeinstra** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/5627431/17289502/498efdec-57da-11e6-9a40-be6ecf7569c1.png)
