### ISSUE TITLE
We need a way to link to the homepage with the map showing a specified exception

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#19]
we need the ability to link to the homepage showing the map for a specified exceptions. ie: http://www.copyrightexceptions.eu/#Art53f

**Comment by mzeinstra** [comment]
What is the use case/urgency for this? It will need a large refactoring of the site to make this possible, as the map does not have access to the URL (it is in an iFrame) and the way the iFrame is constructed doest not allow access to these parameters.

**Comment by paul2keller** [comment]
the use case is simple. to be able to reference (link to) a specific exception. that is very useful in a number of cases. in terms of urgency this is rather low (we should have thought about this earlier) but it is still a desirable feature

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/17291049/e8175c00-57e1-11e6-83c7-86dda6d807ec.png)

**Comment by mzeinstra** [comment]
Link also made available on Country pages:

![image](https://cloud.githubusercontent.com/assets/5627431/17294081/ba37aec6-57f4-11e6-9cb7-8189816b62d5.png)

**Comment by paul2keller** [comment]
fijn dat dat toch mogelijk was!
