### ISSUE TITLE
country pages: the 3 collum list with the exception numbers wastes vertical space 

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#2]
this can be reduced by turing it into a 4 or 5 column list (plus making the font size smaller as discussed in issue #1)

**Comment by mookl** [comment]
I agree with more columns.

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16274821/8f9ee4a2-38a7-11e6-8244-cae8e6acb268.png)
Still pending outcome of #1

**Comment by paul2keller** [comment]
still a lot of unused space. we could either add another column or simply list them all after each other Art. 5.1, art 5.2(a), art 5.2(b), ....

**Comment by mzeinstra** [comment]
4 columns is best value. 5 columns is not possible within the theme.

![image](https://cloud.githubusercontent.com/assets/5627431/16275089/d1076ada-38a8-11e6-9247-a9512a4a82f4.png)

**Comment by paul2keller** [comment]
i think i like the last option best. maybe with a bit more spacing between de individual articles: 

> Art 5.1 |  Art 5.2(a)  |  Art 5.2(b)  |  ....

**Comment by mookl** [comment]
Agreed: more space and a vertical line between the articles.

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16338424/e2a12522-3a1c-11e6-96a9-765ac99c1499.png)

@paul2keller ok to close?

**Comment by paul2keller** [comment]
i think it will look a bit better if we put two spaces inbetween the last letter of the art and the | (and between the | and the next letter). also we should probably underline them to make it clear that they are links

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16372849/3f8f0950-3c4f-11e6-81ee-894ef956b6a9.png)
