### ISSUE TITLE
Table knop bovenin plaatsen?

### ISSUE THREAD

**Issue by mzeinstra** [Kennisland/Copyrightexceptions.eu#20]
Ik heb feedback ontvangen dat de SHOW TABLE knop niet zichtbaar is op te kleine schermen en over het hoofd gezien wordt. Bovenin plaatsen of bij de zoom knoppen plaatsen?

@mookl

**Comment by paul2keller** [comment]
wat mij betreft is dat inderdaad een goede oplossing

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/18131955/05284e42-6f95-11e6-9201-999baa2e1a77.png)

![image](https://cloud.githubusercontent.com/assets/5627431/18131974/19f378f6-6f95-11e6-87e9-33eb0ef8e495.png)
