### ISSUE TITLE
Optioneel, alle Europese landen weer toevoegen?

### ISSUE THREAD

**Issue by mzeinstra** [Kennisland/Copyrightexceptions.eu#24]
Waar willen jullie de grens zetten? Rusland, IJsland erbij?

Het is voor mij teveel werk om Kaliningrad uit Rusland te peuteren, dan heb ik voor de launch nog andere prioriteiten.

Dus voor de launch heel Europa weer toevoegen, Balkan, en Rusland en IJsland

of na de launch rustig kijken wat we willen toevoegen, wat denken jullie?

**Comment by paul2keller** [comment]
rusland en ijsland niet, rest wel

**Comment by mzeinstra** [comment]
Maar wel Kaliningrad? Want dat wordt het na de launch

**Comment by mookl** [comment]
Mee eens. Over K. heb ik geen mening eerlijk gezegd.
