### ISSUE TITLE
country pages: the back to top links in between the text boxes should be removed 

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#3]

**Comment by mookl** [comment]
Why not be helpful to the poor visitor. This page can become very very long...

**Comment by paul2keller** [comment]
why are our vistors poor. what would they want to do at the top of the page? i find these distracting and ugly so can we please remove them?

**Comment by mookl** [comment]
they might want to go back to the index.
but whatever, remove them if you insist.

**Comment by paul2keller** [comment]
i insist

**Comment by mzeinstra** [comment]
Done
