### ISSUE TITLE
country information box on home page: display only those sections that actually contain information

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#4]
<img width="569" alt="screen shot 2016-06-22 at 14 56 28" src="https://cloud.githubusercontent.com/assets/5593766/16267342/9447dec8-3889-11e6-8664-a74bb2910d36.png">

In this example 'implemented on', 'renumeration', article no in local act' and 'remarks' should not be displayed.

**Comment by mzeinstra** [comment]
Weet je het zeker? Zo laten we niet zien wat voor mogelijkheden het platform heeft. Bijvoorbeeld dat je commentaar kan achterlaten.

**Comment by paul2keller** [comment]
yes i am sure that i do not want to show these empty fields. looks incomplete
