### ISSUE TITLE
country information box on home page: display name of the country on top of the box

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#5]
in addition to highlighting the country name on the map.

**Comment by mzeinstra** [comment]
Does not seem to make much sense without also duplicating the name of the exception:

![image](https://cloud.githubusercontent.com/assets/5627431/16274507/27ad9812-38a6-11e6-9feb-4634ac783f90.png)

**Comment by paul2keller** [comment]
not sure. in any case i was more thinking more about a grey box with white text inside (without the Country).

**Comment by mzeinstra** [comment]
@mookl ?

**Comment by mookl** [comment]
I think like this, and maybe it's best to introduce a close-button?

![image](https://cloud.githubusercontent.com/assets/13234593/16332930/ecbd6e9a-39f8-11e6-8f66-8c4a08025b16.png)

**Comment by paul2keller** [comment]
yes i like this much better, but we are still missing an explicit link to the country page (issue #7)

**Comment by paul2keller** [comment]
the design above has not been implemented yet

**Comment by mzeinstra** [comment]
Voor verder discussie in #7
