### ISSUE TITLE
Information displayed on map and country pages does not match

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#6]
see http://dev.copyrightexceptions.eu/Netherlands/#Art52e and 
<img width="1254" alt="screen shot 2016-06-22 at 15 03 28" src="https://cloud.githubusercontent.com/assets/5593766/16267532/8685d2b2-388a-11e6-81eb-2de0565870d5.png">

**Comment by mzeinstra** [comment]
See known issue # 3 on Slack
