### ISSUE TITLE
missing: an obvious link from the homepage / map to the country page

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#7]
now it is hidden in the more information link. we might need a separate "show all exceptions in country x" link as well.

**Comment by mookl** [comment]
Why separate? We could just replace the more info button with a show all exceptions button?

**Comment by paul2keller** [comment]
because they provide separate functionality. the 'more information' link goes to the exception in question on the country page. what i am asking for is a link to the country page. might make more sense to have such a button at the top of the info box next to the country name (see issue #5)

**Comment by mzeinstra** [comment]
Ik heb hier een ontwerp voor nodig. Ik zou het bijvoorbeeld ook in de popup voor het land kunnen stoppen.

**Comment by mookl** [comment]
Maybe an extra button is a bit too much. What about an obvious link?

![image](https://cloud.githubusercontent.com/assets/13234593/16333097/bc2f6dc2-39f9-11e6-84d2-ef31e2c2dd41.png)

**Comment by paul2keller** [comment]
dont like that visually. the buttons at the bottom of the box also do not have a underline and they are links as well. can we try a mockup with an extra button?

**Comment by mookl** [comment]
![image](https://cloud.githubusercontent.com/assets/13234593/16420994/bf683084-3d53-11e6-86ac-56e20d0bac38.png)

PK: "yup"

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16429094/56254ad6-3d75-11e6-9888-7528ef2baffb.png)

**Comment by mookl** [comment]
'Implemented' in the right box should line left with he rest.

**Comment by mookl** [comment]
And the second row of buttons should be placed 1px up.

**Comment by paul2keller** [comment]
also should be capitalized

**Comment by mookl** [comment]
@paul2keller is already capitalized...?

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16447536/62c102e4-3ded-11e6-8919-d568786c307b.png)
