### ISSUE TITLE
missing: licensing information in the footer.

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#8]
everything is CC0 (question: is this compatible with the licensing terms of the map)

**Comment by mzeinstra** [comment]
"All texts and data presented on this website are dedicated to the public domain using Creative Commons Zero."

We kunnen het design en de kaart niet licenseren. Die zijn niet cc0

**Comment by paul2keller** [comment]
onder wat voor een licentie gebruiken we de kaart dan wel?

**Comment by mzeinstra** [comment]
LeafletJS (javascript): https://github.com/Leaflet/Leaflet/blob/master/LICENSE
kaartdata, voor onze eigen aanpassingen zijn PD: http://www.naturalearthdata.com/about/terms-of-use/

Combinatie van de twee werken is niet noodzakelijk PD

**Comment by paul2keller** [comment]
ok maar distribueren we de source code wel? zover ik kan zien linken we vanaf map.html naar een script die ergens anders gehost wordt.
