### ISSUE TITLE
footer: mention that this is a project of Kennisland that has been made possible with support from OSF

### ISSUE THREAD

**Issue by paul2keller** [Kennisland/Copyrightexceptions.eu#9]
right now KL has just a logo but we are not making clear what our role is

**Comment by paul2keller** [comment]
also use the full KL logo (with the word Kennisland)

**Comment by mookl** [comment]
Okay, I will send the logo to Maarten.

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16272692/12142932-389f-11e6-9f26-4533e19f9c52.png)

Like this?

**Comment by mookl** [comment]
2x zo groot minstens (KL-beeldmerk was goede grootte eerst).

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16272818/8f395be4-389f-11e6-9ee9-96158187cd42.png)

**Comment by paul2keller** [comment]
yes like this (there is still too much white space between the end of the text and the logo. also OSF should be a link (and we need to check if they want us to use specific language and their logo)

**Comment by paul2keller** [comment]
actually this is the language that we need to use:

> CopyrightExceptions.eu is a project by Kennisland and is supported by a grant from the Foundation Open Society Institute in cooperation with the Information Program of the Open Society Foundations.

will check with them if they want us to also add their logo

**Comment by mzeinstra** [comment]
@mookl de witruimte zit in de SVG, kan jij een svg aanleveren die dit niet heeft?

**Comment by mookl** [comment]
https://www.dropbox.com/s/tru8xhekbihk9e7/KL_logo_met_tekst_RGB.svg?dl=0

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16338495/5a139f40-3a1d-11e6-8fba-6efbba875f6b.png)

**Comment by paul2keller** [comment]
According to OSF we should use this text:

> CopyrightExceptions.eu is a project by [Kennisland](http://www.kennisland.nl) and is supported by a grant from the [Information Program of the Open Society Foundations](https://www.opensocietyfoundations.org/about/programs/information-program).

**Comment by mzeinstra** [comment]
![image](https://cloud.githubusercontent.com/assets/5627431/16372047/b66aef1c-3c4a-11e6-9a1e-3862ef732a9a.png)
